[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run migration:run && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[start]
cmd = "npm run migration:run && npm run start:prod"
