[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules && npm ci && npm run build"

[deploy]
startCommand = "npm run migration:run && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
